### ISSUE TITLE
Yarn Install Issue

### ISSUE THREAD

**Issue by kendoori** [oae/gnome-shell-minimize-to-tray#10]
I had recently installed from the Gnome Extensions site, but when I saw that there was a new version, I wanted to get the latest and greatest. It's not clear from the Extensions site whether that is there.

I followed the GIT install instructions and when I get to the "yarn install" step this is what I see.

`kenny@pop-os:~/gnome-shell-minimize-to-tray$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
`
Also, when I try to configure, I am presented with this:
![Minimize to Tray_010](https://user-images.githubusercontent.com/2447420/90337369-14894500-dfb0-11ea-8295-9508dc21d06e.png)

The extension still seems to work. BTW, this is exactly what I was looking for.

**Comment by oae** [comment]
Can you share the yarn version?

```sh
yarn -v
```

**Comment by kendoori** [comment]
kenny@pop-os:~$ yarn -v
ERROR: There are no scenarios; must have at least one.

I didn't have Yarn, and the system prompted me to to install: cmdtest

**Comment by oae** [comment]
Since I had it installed, I forgot to mention it in instructions. You need to install [nodejs](https://nodejs.org/en/) and [yarn](https://yarnpkg.com/lang/en/docs/install/) and `gobject-introspection` package for git installation.

**Comment by oae** [comment]
Or if you don't want to bother, you can download [minimize-to-tray@elhan.io.zip
](https://github.com/oae/gnome-shell-minimize-to-tray/releases/tag/v5) and extract its content to `~/.local/share/gnome-shell/extensions/minimize-to-tray@elhan.io` directory. If directory doesn't exist, you can create.

**Comment by kendoori** [comment]
I installed the dependencies but I somehow think the system was confused
and I was never able to build it. After a few tries and a restart of the
shell, I was able install and configure using the download version. It now
runs without error and is definitely the new version as the UI is
different. I am now able to launch a window and pick it to be minimized to
the tray.

Great extension.

**Comment by oae** [comment]
thank you :)

**Comment by kendoori** [comment]
BTW, the version here:
https://extensions.gnome.org/extension/1750/minimize-to-tray/ is still the
old version. I tried this on another computer.

**Comment by oae** [comment]
Yes. The new version is pending approval from reviewers. Also, new features will be available for gnome-shell >= 3.36 version
