### ISSUE TITLE
v5 doesn't seem to work in Ubuntu 20 - gnome-shell 3.36.4

### ISSUE THREAD

**Issue by pabloh84** [oae/gnome-shell-minimize-to-tray#12]
I installed by downloading the zip file, extracting it and copying it to ~/.local/share/gnome-shell/extensions/ and restarting the shell. 

The extension seems to load without errors but nothing happens when the big "+" button is clicked. 

Any logs or anything I can do to help diagnose the problem? LookingGlass shows no errors...

![image](https://user-images.githubusercontent.com/7147388/90599518-4d662b80-e1f5-11ea-97cb-60485cf8209a.png)

**Comment by oae** [comment]
you need to have [dependencies](https://github.com/oae/gnome-shell-minimize-to-tray#requirements) installed for it to work. For logs you can check `journalctl -f /usr/bin/gjs-console`

**Comment by pabloh84** [comment]
That was it! xdotool was missing! 

Sorry about it since it was clearly stated in the instructions but somehow I missed it!

Thanks a lot for your help and your great work!
