### ISSUE TITLE
Auto-complete while searching (or list of all to pick)

### ISSUE THREAD

**Issue by jurosh** [oae/gnome-shell-minimize-to-tray#2]
Would be great to add button to display running apps inside extension - or add suggestions while typing.

I wasn't able to find Thunderbird (as it was Thunderbird Mail), but this helped:

```
d=`date "+%Y-%m-%d %H:%M:%S"` && busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'global.get_window_actors().forEach(w => {const app = Shell.WindowTracker.get_default().get_window_app(w.metaWindow); if(app) log(`app-names:${app.get_name()}`)});' > /dev/null  2>&1 && journalctl /usr/bin/gnome-shell --since "`echo $d`" -o cat | grep 'app-names' | cut -f 2 -d ':'
```

That command is not listed on Gnome extensions page, so would be good to include it or add support for autocomplete when searching.

Probably best would be to list all running apps but keep those as DISABLED, so user can just tick which want :)

**Comment by oae** [comment]
I have added the feature to the new version. It should be available in the EGO after the review process is finished.

![image](https://user-images.githubusercontent.com/1043714/56380774-b6ade700-621b-11e9-8a58-e732897163f2.png)

**Comment by jurosh** [comment]
Wow! That was super quick.

And by looking into change it's very nicely done. Was thinking how to create such thing but probably need to study Gnome components a little bit more :)
