### ISSUE TITLE
[Feature] Close to tray and startup on tray

### ISSUE THREAD

**Issue by 7system7** [oae/gnome-shell-minimize-to-tray#4]
It would be cool, if we could close the affected apps to tray. So we clicked on the close btn or we use the alt + f4 shortcut, after that the app is closing to tray. :)

It may be a good feature if we could choose apps, that is starting minimized on tray.

**Comment by oae** [comment]
It is a great idea but I couldn't find a way to intercept close action on a window. But I could add minimize on start feature

**Comment by oae** [comment]
I have added an option in settings for `hidden on start`. The feature will be released in v6 version
