### ISSUE TITLE
error at the start

### ISSUE THREAD

**Issue by cantaro86** [oae/gnome-shell-minimize-to-tray#6]
Hi.  I have the following error:

> SyntaxError: class is a reserved identifier
> Stack trace:
>  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:79
>  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:94
>  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
>  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
>  main@resource:///org/gnome/shell/extensionPrefs/main.js:397

**Comment by oae** [comment]
Thank you for the feedback. Which Gnome version are you using?

**Comment by cantaro86** [comment]
I'm using Ubuntu 16.04 with GNOME Shell 3.18.5

**Comment by cantaro86** [comment]
Any ideas on how i can fix it?
Thanks

**Comment by oae** [comment]
I am not planning to add support for old versions on gnome-shell.
