### ISSUE TITLE
Minimized applications keep poping up

### ISSUE THREAD

**Issue by error23** [oae/gnome-shell-minimize-to-tray#8]
I don't know if is plugin or something else but when i minimize one app to try it stay minimized but after few seconds it maximize itself

Fedora 32 (Workstation Edition)
Gnome 3.36.3

**Comment by oae** [comment]
Thank you for the feedback. I am in the process of re-writing the extension. It will fix this issue also.

**Comment by JayBeeDe** [comment]
I also have the same issue on Ubuntu 18 : windows reappear randomly (one by one or all at the same time when unlocking gnome session)

**Comment by Honza-m** [comment]
Hi, not sure if it's the same issue but sounds similar enough - My apps maximize randomly every couple of minutes (but sometimes longer). They always seem to maximize as I hit a keyboard key but I couldn't find a pattern... 

Ubuntu 19.04, Gnome 3.36.3, minimizing the Evolution mail client.

**Comment by JayBeeDe** [comment]
> Thank you for the feedback. I am in the process of re-writing the extension. It will fix this issue also.

@oae When will you release the re-written extension ? Do you need help for that ?
Is it worth it to try to fix the current version extension in the meantime ?

**Comment by oae** [comment]
> > Thank you for the feedback. I am in the process of re-writing the extension. It will fix this issue also.
> 
> @oae When will you release the re-written extension ? Do you need help for that ?
> Is it worth it to try to fix the current version extension in the meantime ?

Sorry for the late response, I finished the rewriting. It should be up in a few days on EGO.
